apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hello-world-bjh1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hello-world-bjh1
    app.kubernetes.io/part-of: test-app-qelv
  name: devfile-sample-hello-world-bjh1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: devfile-sample-hello-world-bjh1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: devfile-sample-hello-world-bjh1
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-dnyd-tenant/test-app-qelv/devfile-sample-hello-world-bjh1@sha256:b90c5bc54a47906834324e63eb1e46caa8ba772f10eea53af44a9d62d8fb67aa
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
