apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hello-world-bjh1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-dnyd-tenant/test-app-qelv/devfile-sample-hello-world-bjh1@sha256:b90c5bc54a47906834324e63eb1e46caa8ba772f10eea53af44a9d62d8fb67aa
        name: my-nginx
        resources: {}
status: {}
